development:
  exporter:
    docraptor:
      api_key: ws2lXv8oOnUBK0V75D
    pdfcrowd:
      username: wakalord
      api_key: 91004a27978dd61416da547373f447b0

production:
  exporter:
    docraptor:
      api_key: ws2lXv8oOnUBK0V75D
    pdfcrowd:
      username: wakalord
      api_key: 91004a27978dd61416da547373f447b0

test:
  exporter:
    docraptor:
      api_key: ws2lXv8oOnUBK0V75D
    pdfcrowd:
      username: wakalord
      api_key: 91004a27978dd61416da547373f447b0
